// Generated by CoffeeScript 1.9.1
var binary;

binary = require('../parsearray/binary');

module.exports = function(data) {
  return {
    byte: function(n, cb) {
      return data.read(n, function(b) {
        var j, results;
        return cb((function() {
          results = [];
          for (var j = 0; 0 <= n ? j < n : j > n; 0 <= n ? j++ : j--){ results.push(j); }
          return results;
        }).apply(this).map(function(i) {
          return b[i];
        }));
      });
    },
    hex: function(n, cb) {
      return data.read(n, function(b) {
        var j, results;
        return cb((function() {
          results = [];
          for (var j = 0; 0 <= n ? j < n : j > n; 0 <= n ? j++ : j--){ results.push(j); }
          return results;
        }).apply(this).map(function(i) {
          return b[i].toString(16);
        }));
      });
    },
    char: function(n, cb) {
      return data.read(n, function(b) {
        return cb(binary.readString(b).substr(0, n));
      });
    },
    short: function(n, cb) {
      return data.read(2 * n, function(b) {
        var i, j, ref, res;
        for (i = j = 0, ref = n; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
          res = binary.readShort(b, 2 * i);
        }
        return cb(res);
      });
    },
    int: function(n, cb) {
      return data.read(4 * n, function(b) {
        var i, res;
        res = (function() {
          var j, ref, results;
          results = [];
          for (i = j = 0, ref = n; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
            results.push(binary.readInt(b, 4 * i));
          }
          return results;
        })();
        return cb(res);
      });
    },
    float: function(n, cb) {
      return data.read(4 * n, function(b) {
        var i, j, ref, res;
        for (i = j = 0, ref = n; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
          res = binary.readFloat(b, 4 * i);
        }
        return cb(res);
      });
    },
    double: function(n, cb) {
      return data.read(8 * n, function(b) {
        var i, j, ref, res;
        for (i = j = 0, ref = n; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
          res = binary.readDouble(b, 8 * i);
        }
        return cb(res);
      });
    }
  };
};
