// Generated by CoffeeScript 1.9.1
var readbinary;

readbinary = require('../util/readbinary');

module.exports = function(data) {
  var primatives;
  return primatives = {
    byte: function(cb) {
      return data.read(1, function(b) {
        return cb(readbinary.byte(b));
      });
    },
    char: function(cb) {
      return data.read(1, function(b) {
        return cb(readbinary.char(b));
      });
    },
    short: function(cb) {
      return data.read(2, function(b) {
        return cb(readbinary.short(b));
      });
    },
    int: function(cb) {
      return data.read(4, function(b) {
        return cb(readbinary.int(b));
      });
    },
    bigint: function(cb) {
      return data.read(8, function(b) {
        return cb(readbinary.bigint(b));
      });
    },
    float: function(cb) {
      return data.read(4, function(b) {
        return cb(readbinary.float(b));
      });
    },
    double: function(cb) {
      return data.read(8, function(b) {
        return cb(readbinary.double(b));
      });
    }
  };
};
