// Generated by CoffeeScript 1.9.1
var Body, Header;

Header = require('./src/header');

Body = require('./src/body');

module.exports = {
  header: function(data) {
    return new Header(data).header();
  },
  body: function(data, header, index) {
    return new Body(data).body(header, index);
  }
};
