// Generated by CoffeeScript 1.9.1
module.exports = {
  header: require('./src/structure/readheader'),
  records: require('./src/structure/readrecords'),
  variable: require('./src/structure/readvariable')
};
