// Generated by CoffeeScript 1.8.0
var TA, filename, req;

TA = require('typedarray');

filename = 's20150211_12z.nc';

req = new XMLHttpRequest();

req.responseType = 'arraybuffer';

req.addEventListener('progress', function(e) {
  if (e.lengthComputable != null) {
    return console.log((e.loaded / e.total).toFixed(2));
  }
});

req.addEventListener('load', function(e) {
  return window.netcdf(new TA.Uint8Array(req.response));
});

req.open('GET', filename, true);

req.send(null);
