// Generated by CoffeeScript 1.9.1
var buf, data, fs, header, netcdf;

fs = require('fs');

netcdf = require('./index');

buf = fs.readFileSync('./examples/madis-maritime.nc', {
  encoding: null
});

data = new Uint8Array(buf);

header = netcdf.header(data);

console.log(JSON.stringify(header, null, 2));
