// Generated by CoffeeScript 1.9.1
var b, file, netcdf, readfile, readrandom, readstream, start;

readfile = require('./src/readfile');

readstream = require('./src/readstream');

readrandom = require('./src/readrandom');

netcdf = require('./index');

file = './examples/s20150211_12z.nc';

b = readrandom(file);

start = process.hrtime();

netcdf.header(b, function(header) {
  var delta;
  delta = process.hrtime(start);
  return console.log(delta[0] + "s " + (delta[1] / 1000000) + "ms");
});
