// Generated by CoffeeScript 1.9.1
var b, readstream;

readstream = require('./src/readstream');

b = readstream('./examples/singledim.nc');

b.read(1, function(buf) {
  return console.log(buf);
});

b.read(1, function(buf) {
  return console.log(buf);
});

b.read(1, function(buf) {
  return console.log(buf);
});

b.read(1, function(buf) {
  return console.log(buf);
});
