// Generated by CoffeeScript 1.9.2
var file, headerbuffer, netcdf, readrandom, readstream;

readstream = require('../fs/readstream');

readrandom = require('../fs/readrandom');

netcdf = require('../');

file = './examples/WMI_Lear.nc';

headerbuffer = readstream(file);

netcdf.readheader(headerbuffer, function(header) {
  var randombuffer;
  console.log(JSON.stringify(header, null, 2));
  randombuffer = readrandom(file);
  netcdf.readvariable(header, randombuffer, 'lat', function(err, data) {
    if (err != null) {
      return console.error(err);
    }
    return console.log(data);
  });
  return netcdf.readrecords(header, randombuffer, function(err, data) {
    if (err != null) {
      return console.error(err);
    }
    return console.log(data);
  });
});
