// Generated by CoffeeScript 1.9.1
var readdimension;

readdimension = require('./readdimension');

module.exports = function(header, buffer, cb) {
  var readslab;
  if (header.records.number === 0) {
    return cb(new Error('No records'));
  }
  readslab = function(result, position, content) {
    var name, offset, ref, results;
    ref = header.records.offsets;
    results = [];
    for (name in ref) {
      offset = ref[name];
      results.push(result[name].push(readdimension(content, position + offset, header.variables[name])));
    }
    return results;
  };
  buffer.go(header.records.offset);
  return buffer.read(header.records.size * header.records.number, function(content) {
    var _, i, j, key, ref, ref1, result;
    result = {};
    ref = header.records.offsets;
    for (key in ref) {
      _ = ref[key];
      result[key] = [];
    }
    for (i = j = 0, ref1 = header.records.number; 0 <= ref1 ? j < ref1 : j > ref1; i = 0 <= ref1 ? ++j : --j) {
      readslab(result, i * header.records.size, content);
    }
    return cb(null, result);
  });
};
