// Generated by CoffeeScript 1.8.0
var Body, Lexer, util,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Lexer = require('./lexer');

util = require('./util');

Body = (function() {
  function Body(data) {
    this.body = __bind(this.body, this);
    this.lex = new Lexer(data);
  }

  Body.prototype.body = function(header, index) {
    var dimensions, key, variable;
    key = Object.keys(header.variables)[index];
    variable = header.variables[key];
    dimensions = variable.dimensions.map(function(i) {
      return header.dimensions[i];
    });
    return {
      key: key,
      variable: variable,
      dimensions: dimensions
    };
  };

  return Body;

})();

module.exports = function(data, header, index) {
  return new Body(data).body(header, index);
};
