// Generated by CoffeeScript 1.8.0
module.exports = {
  streamingMarker: [255, 255, 255, 255],
  zeroMarker: [0, 0, 0, 0],
  dimensionMarker: [0, 0, 0, 10],
  variableMarker: [0, 0, 0, 11],
  attributeMarker: [0, 0, 0, 12],
  byteMarker: [0, 0, 0, 1],
  charMarker: [0, 0, 0, 2],
  shortMarker: [0, 0, 0, 3],
  intMarker: [0, 0, 0, 4],
  floatMarker: [0, 0, 0, 5],
  doubleMarker: [0, 0, 0, 6],
  charFill: [0],
  byteFill: [129],
  shortFill: [128, 129],
  intFill: [128, 0, 0, 1],
  floatFill: [124, 240, 0, 0],
  doubleFill: [71, 158, 0, 0, 0, 0, 0, 0]
};
