// Generated by CoffeeScript 1.9.1
var binary;

binary = require('./binary');

module.exports = function(data) {
  var primatives;
  return primatives = {
    byte: function(cb) {
      return data.read(1, function(b) {
        return cb(binary.readByte(b));
      });
    },
    char: function(cb) {
      return data.read(1, function(b) {
        return cb(binary.readChar(b));
      });
    },
    short: function(cb) {
      return data.read(2, function(b) {
        return cb(binary.readShort(b));
      });
    },
    int: function(cb) {
      return data.read(4, function(b) {
        return cb(binary.readInt(b));
      });
    },
    float: function(cb) {
      return data.read(4, function(b) {
        return cb(binary.readFloat(b));
      });
    },
    double: function(cb) {
      return data.read(8, function(b) {
        return cb(binary.readDouble(b));
      });
    }
  };
};
