// Generated by CoffeeScript 1.9.1
module.exports = function(buffer) {
  var ends, index, length;
  index = 0;
  length = buffer;
  ends = [];
  return {
    close: function() {},
    read: function(n, cb) {
      var e, j, len, result;
      if (index + n >= length) {
        for (j = 0, len = ends.length; j < len; j++) {
          e = ends[j];
          e();
        }
        ends = [];
        return;
      }
      index += n;
      if (cb != null) {
        result = new Uint8Array(buffer, index - n, n);
        return cb(result);
      }
    },
    go: function(i) {
      return index = i;
    },
    on: function(e, cb) {
      if (e === 'end') {
        return ends.push(cb);
      }
    }
  };
};
