// Generated by CoffeeScript 1.9.1
var TA;

TA = require('typedarray');

module.exports = function(buffer) {
  var ends, index, length;
  index = 0;
  length = buffer;
  ends = [];
  return {
    read: function(n, cb) {
      var e, i, len;
      if (index + n >= length) {
        for (i = 0, len = ends.length; i < len; i++) {
          e = ends[i];
          e();
        }
        ends = [];
        return;
      }
      index += n;
      return cb(new TA.Uint8Array(buffer, index - n, n));
    },
    on: function(e, cb) {
      if (e === 'end') {
        return ends.push(cb);
      }
    }
  };
};
