// Generated by CoffeeScript 1.9.1
module.exports = function(num, multiple) {
  var remainder;
  if (multiple === 0) {
    return num;
  }
  remainder = num % multiple;
  if (remainder === 0) {
    return num;
  }
  return num + multiple - remainder;
};
