// Generated by CoffeeScript 1.9.1
var fs;

fs = require('fs');

module.exports = function(file) {
  var drain, read, requests;
  read = fs.createReadStream(file);
  requests = [];
  drain = function() {
    var chunk, request;
    if (requests.length === 0) {
      return;
    }
    request = requests[0];
    chunk = read.read(request.bytes);
    if (chunk === null) {
      return;
    }
    requests.shift();
    if (request.cb != null) {
      request.cb(new Uint8Array(chunk));
    }
    return drain();
  };
  read.on('readable', function() {
    return drain();
  });
  return {
    close: function() {
      return read.destroy();
    },
    read: function(n, cb) {
      requests.push({
        bytes: n,
        cb: cb
      });
      return drain();
    },
    on: function(e, cb) {
      return read.on(e, cb);
    }
  };
};
